In [1]:
import numpy as np
import pandas as pd 


# data

In [2]:
R = np.array([[4,0,2,0,1],
             [0,2,3,0,0],
             [1,0,2,4,0],
             [5,0,0,3,1],
             [0,0,1,5,1],
             [0,3,2,4,1],])

# algorithm

In [3]:
"""
R
K
steps
alpha
lamda


output:
P*Q

"""

'\nR\nK\nsteps\nalpha\nlamda\n\n\noutput:\nP*Q\n\n'

In [4]:
K=2
max_iter=5000
alpha=0.00002
lamda=0.0004


In [21]:
def LFM_grad_desc(R,K=2,max_iter=1000,alpha=0.0001,lamda=0.002):
    M=len(R)
    N=len(R[0])
    
    P=np.random.rand(M,K)
    Q=np.random.rand(N,K)
    Q=Q.T
    #start iter
    for step in range(max_iter):
        for u in range(M):
            for i in range(N):
                if R[u][i]>0:
                    eui=np.dot(P[u,:],Q[:,i])-R[u][i]
                    for k in range(K):
                        P[u][k]=P[u][k]-alpha*(2*eui*Q[k][i]+2*lamda*P[u][k])
                        Q[k][i]=Q[k][i]-alpha*(2*eui*P[u][k]+2*lamda*Q[k][i])
                        

        cost = 0
        for u in range(M):
            for i in range(N):
                if R[u][i] > 0:
                    cost += ( np.dot( P[u,:], Q[:,i] ) - R[u][i] ) ** 2
                    # 加上正则化项
                    for k in range(K):
                        cost += lamda * ( P[u][k] ** 2 + Q[k][i] ** 2 )
        if cost < 0.0001:
            break
    
    return P,Q.T,cost

In [22]:
P, Q, cost = LFM_grad_desc(R, K, max_iter, alpha, lamda)

print(P)
print(Q)
print(cost)

predR = P.dot(Q.T)

print(R)
predR

[[1.05376323 1.27414167]
 [1.36742843 0.39205407]
 [1.29686186 0.63157545]
 [1.03447427 1.48513412]
 [0.86908028 1.14893587]
 [1.01776442 1.23303216]]
[[0.95753874 1.59476233]
 [0.70521084 1.2260704 ]
 [1.45202167 0.41116575]
 [1.67372367 1.67415327]
 [0.7369553  0.23524741]]
12.194721215036504
[[4 0 2 0 1]
 [0 2 3 0 0]
 [1 0 2 4 0]
 [5 0 0 3 1]
 [0 0 1 5 1]
 [0 3 2 4 1]]


array([[3.04097226, 2.30531264, 2.05397047, 3.89681692, 1.07631492],
       [1.93459876, 1.44501123, 2.14673492, 2.94505593, 1.09996333],
       [2.24900822, 1.68891701, 2.14275373, 3.22794251, 1.10430571],
       [3.35898514, 2.55040145, 2.11271535, 4.21776622, 1.11173525],
       [2.66445769, 2.0215611 , 1.73432648, 3.37809499, 0.9107575 ],
       [2.94094211, 2.22952274, 1.9847966 , 3.76774124, 1.04011451]])